# Generated by Django 6.0.3 on 2026-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="recipe_covers/"),
        ),
    ]
