# Generated by Django 6.0.3 on 2026-03-29 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_cover_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "recipe")},
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "recipe"], name="recipes_lik_user_id_2a2a10_idx"
            ),
        ),
    ]
